http:
  routers:
    app-api:
      rule: "PathPrefix(`/api/app`)"
      service: app-api
      priority: 100
    client:
      rule: "PathPrefix(`/`)"
      service: client
      priority: 1

  services:
    app-api:
      loadBalancer:
        servers:
          - url: "http://api-service:8000"
    client:
      loadBalancer:
        servers:
          - url: "http://client:5173"
